### ISSUE TITLE
individually configurable joint geometrys

### ISSUE THREAD

**Issue by friebelt** [max-sn/robotarm#1]
Hi,
the manual shows how to set a new style for the joint with \pgfkeys. Is this always global, or can it be applied to a single joint? We would like to change the first joint and represeent it as a sqare for example since it is rotating orthogonal to the other axes.

Tanks for the easy to use library,
Tobi

**Comment by max-sn** [comment]
Hi Tobi,

Apologies for the late reply. Unfortunately this is not really supported, but you can use a workaround by redefining `robotarm/link/draw joint` and make it conditional on `\link@num` (which is used as iterator when actually drawing the links).

For example, this:

```latex
\documentclass[tikz, margin=1mm]{standalone}

\usepackage{robotarm}

\begin{document}
  \begin{tikzpicture}
    \makeatletter
    \robotArm[draw annotations=false,
      link/draw joint/.code={
        \ifnum\link@num=1
          \path[link style]
            (-\RA@link@jointradius, -\RA@link@jointradius)
            rectangle
            (\RA@link@jointradius, \RA@link@jointradius);
        \else%
          \path[link style]
            (0,0) circle (\RA@link@jointradius);
          \path[link style]
            (0,0) circle (1/3*\RA@link@jointradius);
        \fi
      },
      config={q1=90,q2=-70,q3=-60},
      geometry={a1=1.75,a2=1.5,a3=1}]{3}
    \makeatother
  \end{tikzpicture}
\end{document}
```

Results in:
![image](https://github.com/max-sn/robotarm/assets/38857185/f529bba5-7402-4da6-8dd8-e46f848de30a)

Please let me know if this is workaround is sufficient for your use case.

Max

**Comment by apuszkar** [comment]
Hi Max,

works like a charm! Thank you.

![grafik](https://github.com/max-sn/robotarm/assets/136347354/5bee4337-cc5e-4517-b8bb-398e0b1b4940)

Since Tobi asked for me, you can consider the Question answered.

Andreas

**Comment by max-sn** [comment]
Looking great!
