### ISSUE TITLE
any way to remove the link lengths and joint angles?

### ISSUE THREAD

**Issue by ntorresalberto** [max-sn/robotarm#2]
Hi, first of all, thanks for this great package.
I was wondering if there's an easy way to obtain something like this?

![2023-06-01-01:41:38-screenshot](https://github.com/max-sn/robotarm/assets/63748204/b421064f-eed5-4f42-bab3-86f6a86ddb8c)

**Comment by max-sn** [comment]
Hi,
Absolutely! You can use the key `draw annotations` and set it to `false` (it is `true` by default).

For example, this:

```latex
\documentclass[tikz, margin=1mm]{standalone}

\usepackage{robotarm}

\begin{document}
  \begin{tikzpicture}
    \makeatletter
    \robotArm[
      draw annotations=false,
      config={q1=90,q2=-70,q3=-60},
      geometry={a1=1.75,a2=1.5,a3=1}]{3}
    \makeatother
  \end{tikzpicture}
\end{document}
```

Results in:
![image](https://github.com/max-sn/robotarm/assets/38857185/dcc08bd9-820e-4214-b09b-ccf4c8576cac)

**Comment by ntorresalberto** [comment]
It worked great, thanks!
